import { Establishment, Category, Specialty, SyncRow, SyncLog, Review, CeramicEvent, Product, PlanConfig, SuggestedSpace, IntegrationConfig } from './types';

export const CATEGORIES: Category[] = [
  'Ateliê',
  'Ateliê Escola',
  'Ceramista',
  'Professor',
  'Escola',
  'Fornecedor',
  'Fabricante',
  'Importador',
  'Loja',
  'Assistência Técnica',
  'Queima',
  'Museu',
  'Galeria',
  'Coworking',
  'Residência',
  'Evento',
  'Feira',
  'Coletivo',
  'Associação',
  'Universidade',
  'Outro'
];

export const SPECIALTIES: Specialty[] = [
  'Modelagem Manual',
  'Torno',
  'Porcelana',
  'Escultura',
  'Azulejaria',
  'Barbotina',
  'Moldagem',
  'Joalheria Cerâmica',
  'Cerâmica Contemporânea',
  'Cerâmica Popular',
  'Cerâmica Indígena',
  'Raku',
  'Naked Raku',
  'Pit Fire',
  'Anagama',
  'Noborigama',
  'Queima Elétrica',
  'Queima a Gás',
  'Queima a Lenha',
  'Alta Temperatura',
  'Baixa Temperatura',
  'Impressão 3D',
  'Restauro'
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'r1',
    establishmentId: 'e1',
    userName: 'Mariana Silva',
    rating: 5,
    comment: 'Ateliê maravilhoso! Fiz o workshop de torno e me apaixonei. O instrutor é super paciente e o espaço tem uma energia fantástica.',
    date: '2026-06-15',
    reply: 'Obrigado, Mariana! É sempre um prazer compartilhar a paixão pelo torno com pessoas tão dedicadas. Volte sempre!'
  },
  {
    id: 'r2',
    establishmentId: 'e1',
    userName: 'Carlos Souza',
    rating: 4,
    comment: 'Excelente seleção de esmaltes e queimas sempre muito precisas. Recomendo o serviço de queima de alta temperatura.',
    date: '2026-06-20'
  },
  {
    id: 'r3',
    establishmentId: 'e2',
    userName: 'Beatriz Costa',
    rating: 5,
    comment: 'As peças do ateliê em Cunha são espetaculares. A queima em Noborigama traz efeitos únicos nas cinzas que parecem pinturas. Um tesouro nacional.',
    date: '2026-05-10'
  },
  {
    id: 'r4',
    establishmentId: 'e3',
    userName: 'Roberto Oliveira',
    rating: 5,
    comment: 'Argila de excelente plasticidade e atendimento nota 10. Pascoal é uma referência nacional para nós ceramistas.',
    date: '2026-06-25'
  }
];

export const INITIAL_ESTABLISHMENTS: Establishment[] = [
  {
    id: 'e1',
    name: 'Ateliê Terra Vermelha',
    category: 'Ateliê Escola',
    specialties: ['Torno', 'Modelagem Manual', 'Alta Temperatura', 'Queima Elétrica', 'Cerâmica Contemporânea'],
    services: ['Cursos Regulares', 'Workshops', 'Serviço de Queima', 'Coworking'],
    privacy: 'full',
    address: 'Rua Harmonia, 1250',
    neighborhood: 'Vila Madalena',
    city: 'São Paulo',
    state: 'SP',
    coordinates: [-23.5532, -46.6891],
    description: 'Um espaço de criação e ensino focado no ensino da cerâmica de alta temperatura com torno elétrico e modelagem livre.',
    longDescription: 'Fundado em 2018 na pulsante Vila Madalena, o Ateliê Terra Vermelha nasceu com o propósito de aproximar as pessoas do fazer manual através da argila. Contamos com 8 tornos elétricos de última geração, cabine de esmaltação profissional, forno elétrico para queimas até 1240°C e uma biblioteca especializada. Oferecemos cursos mensais, oficinas de final de semana, além de planos de coworking para ceramistas independentes que precisam de infraestrutura para produzir suas próprias coleções.',
    instagram: '@atelie_terravermelha',
    whatsapp: '11988887777',
    website: 'https://atelieterravermelha.com.br',
    email: 'contato@atelieterravermelha.com.br',
    phone: '11 3812-4455',
    photo: 'https://images.unsplash.com/photo-1565192647048-f997ded879f9?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1565192647048-f997ded879f9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1610905045094-ab6c18f50685?auto=format&fit=crop&w=800&q=80'
    ],
    cover: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=1200&q=80',
    logo: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=150&q=80',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
    isPremium: true,
    claimed: true,
    ownerId: 'owner123',
    rating: 4.8,
    reviewsCount: 15,
    hours: 'Terça a Sábado: 09:00 às 18:00\nQuinta (noturno): 19:00 às 22:00',
    viewsCount: 342,
    clicksWhatsApp: 89,
    clicksRoute: 45,
    events: [
      {
        id: 'ev1',
        title: 'Imersão no Torno Elétrico',
        type: 'workshop',
        date: '2026-07-11',
        time: '09:30 - 16:30',
        price: 'R$ 480',
        instructor: 'Juliana Paes',
        description: 'Um dia intenso dedicado às técnicas fundamentais de centralização, abertura e elevação de cilindros e tigelas.',
        location: 'No ateliê principal',
        establishmentId: 'e1'
      },
      {
        id: 'ev2',
        title: 'Mesa Posta e Modelagem Manual',
        type: 'curso',
        date: '2026-07-18',
        time: '14:00 - 17:00',
        price: 'R$ 320',
        instructor: 'Felipe Santos',
        description: 'Desenvolvimento de pratos, travessas e xícaras utilizando técnicas de placas, beliscão e rolinhos.',
        location: 'Sala B de Modelagem',
        establishmentId: 'e1'
      }
    ],
    products: [
      {
        id: 'p1',
        name: 'Caneca Rústica Areia - 300ml',
        price: 85,
        photo: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=500&q=80',
        category: 'peca',
        description: 'Caneca utilitária modelada no torno, com argila com sardonix e esmalte fosco texturizado.'
      },
      {
        id: 'p2',
        name: 'Vaso Orgânico Terracota',
        price: 180,
        photo: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=500&q=80',
        category: 'peca',
        description: 'Vaso escultural feito por modelagem manual com argila terracota crua e detalhes polidos.'
      }
    ]
  },
  {
    id: 'e2',
    name: 'Ateliê Floresta e Fogo - Cunha Woodfire',
    category: 'Ateliê',
    specialties: ['Noborigama', 'Queima a Lenha', 'Alta Temperatura', 'Cerâmica Popular', 'Escultura'],
    services: ['Venda de Peças Autoriais', 'Visita Agendada', 'Residências Artísticas'],
    privacy: 'neighborhood',
    address: 'Rodovia Cunha-Paraty, Km 50',
    neighborhood: 'Vila Rica',
    city: 'Cunha',
    state: 'SP',
    coordinates: [-23.0768, -44.9542],
    description: 'Ateliê tradicional focado na mística queima a lenha em forno Noborigama de quatro câmaras. Peças exclusivas marcadas pelas cinzas.',
    longDescription: 'Situado no topo das montanhas de Cunha, polo nacional da cerâmica de alta temperatura, o Ateliê Floresta e Fogo produz peças utilitárias e artísticas queimadas a lenha a 1300°C. O forno Noborigama é aceso apenas três vezes ao ano em um processo comunitário ritualístico que dura mais de 30 horas ininterruptas. Nossas peças carregam o registro natural do sopro do fogo e do depósito de cinzas derretidas, gerando esmaltes naturais irrepetíveis. Aceitamos visitas sob agendamento e realizamos residências artísticas de curta duração.',
    instagram: '@florestaefogo_cunha',
    whatsapp: '1299776655',
    website: 'https://florestaefogocunha.art',
    email: 'contato@florestaefogocunha.art',
    photo: 'https://images.unsplash.com/photo-1449244408244-aaee2b4fc061?auto=format&fit=crop&w=800&q=80',
    isPremium: true,
    claimed: true,
    ownerId: 'owner456',
    rating: 5.0,
    reviewsCount: 38,
    hours: 'Sexta a Domingo: 10:00 às 17:00\nSegunda a Quinta: Visitas agendadas',
    viewsCount: 512,
    clicksWhatsApp: 120,
    clicksRoute: 76,
    events: [
      {
        id: 'ev3',
        title: 'Abertura de Fornada Noborigama',
        type: 'encontro',
        date: '2026-08-05',
        time: '10:00 - 15:00',
        price: 'Gratuito',
        description: 'Participe do emocionante momento de descarregar o forno. Centenas de peças únicas serão reveladas ao público pela primeira vez.',
        location: 'Área do Forno Noborigama',
        establishmentId: 'e2'
      }
    ]
  },
  {
    id: 'e3',
    name: 'Casa do Ceramista Pascoal',
    category: 'Fornecedor',
    specialties: ['Alta Temperatura', 'Baixa Temperatura', 'Barbotina', 'Queima Elétrica', 'Queima a Gás'],
    services: ['Venda de Argilas', 'Esmaltes', 'Ferramentas', 'Fornos', 'Assistência Técnica'],
    privacy: 'full',
    address: 'Av. Ricardo Jafet, 1850',
    neighborhood: 'Ipiranga',
    city: 'São Paulo',
    state: 'SP',
    coordinates: [-23.5925, -46.6212],
    description: 'O maior fornecedor de insumos cerâmicos da grande São Paulo. Argilas nacionais e importadas, corantes, esmaltes e fornos.',
    instagram: '@casadoceramistapascoal',
    whatsapp: '11977771111',
    website: 'https://pascoalceramica.com.br',
    phone: '11 5061-2299',
    photo: 'https://images.unsplash.com/photo-1520406580146-05d83ef31675?auto=format&fit=crop&w=800&q=80',
    isPremium: false,
    claimed: false,
    rating: 4.5,
    reviewsCount: 88
  },
  {
    id: 'e4',
    name: 'Ateliê do Jequitinhonha - Mestra Zezinha',
    category: 'Ceramista',
    specialties: ['Cerâmica Popular', 'Modelagem Manual', 'Baixa Temperatura', 'Escultura'],
    services: ['Venda de Bonecas de Barro', 'Oficinas de Modelagem Popular'],
    privacy: 'neighborhood',
    address: 'Praça Central, S/N',
    neighborhood: 'Coqueiro Campo',
    city: 'Minas Novas',
    state: 'MG',
    coordinates: [-17.2185, -42.5912],
    description: 'Produção das famosas noivas e bonecas de barro do Vale do Jequitinhonha. Técnica ancestral de pintura com pigmentos minerais locais (tauá).',
    instagram: '@mestrazezinhajequitinhonha',
    whatsapp: '38988223344',
    photo: 'https://images.unsplash.com/photo-1590736969955-71cb94801750?auto=format&fit=crop&w=800&q=80',
    isPremium: false,
    claimed: true,
    rating: 4.9,
    reviewsCount: 22
  },
  {
    id: 'e5',
    name: 'Ateliê Porto da Argila',
    category: 'Ateliê',
    specialties: ['Torno', 'Porcelana', 'Alta Temperatura', 'Queima Elétrica'],
    services: ['Cursos Regulares', 'Queima Compartilhada'],
    privacy: 'neighborhood',
    address: 'Rua Fernando Machado, 450',
    neighborhood: 'Centro Histórico',
    city: 'Porto Alegre',
    state: 'RS',
    coordinates: [-30.0345, -51.2312],
    description: 'Estúdio dedicado à alta precisão do torno elétrico e à delicadeza da porcelana translúcida.',
    instagram: '@portodaargila',
    whatsapp: '51981223344',
    photo: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    isPremium: false,
    claimed: false,
    rating: 4.7,
    reviewsCount: 12
  },
  {
    id: 'e6',
    name: 'Cerâmica Artística Marajoara - Mestre Carlos',
    category: 'Ceramista',
    specialties: ['Cerâmica Popular', 'Cerâmica Indígena', 'Modelagem Manual', 'Escultura'],
    services: ['Demonstrações de Torno', 'Venda de Réplicas Arqueológicas', 'Aulas de Pintura Indígena'],
    privacy: 'full',
    address: 'Travessa 15 de Novembro, 88',
    neighborhood: 'Icaraí',
    city: 'Soure',
    state: 'PA',
    coordinates: [-0.7188, -48.5135],
    description: 'Preservação da milenar arte cerâmica marajoara e tapajônica. Peças gravadas à mão com engobes coloridos coletados na Ilha de Marajó.',
    instagram: '@marajoaracarlos',
    whatsapp: '91983334455',
    photo: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    isPremium: true,
    claimed: true,
    ownerId: 'ownerMarajoara',
    rating: 4.9,
    reviewsCount: 54,
    hours: 'Segunda a Sábado: 08:00 às 18:00\nDomingo: 08:00 às 12:00',
    viewsCount: 220,
    clicksWhatsApp: 45,
    clicksRoute: 31
  },
  {
    id: 'e7',
    name: 'Museu da Cerâmica de Cunha',
    category: 'Museu',
    specialties: ['Cerâmica Contemporânea', 'Noborigama', 'Queima a Lenha', 'Restauro'],
    services: ['Visitas Guiadas', 'Exposições Temporárias', 'Pesquisa Histórica'],
    privacy: 'full',
    address: 'Rua Dr. Getúlio Vargas, 145',
    neighborhood: 'Centro',
    city: 'Cunha',
    state: 'SP',
    coordinates: [-23.0741, -44.9602],
    description: 'Espaço dedicado à história e preservação da cerâmica de Cunha, desde o artesanato de panelas de barro tradicional até as modernas queimas em Noborigama.',
    instagram: '@museudaceramicacunha',
    whatsapp: '12999991111',
    website: 'https://museudaceramicadecunha.org.br',
    photo: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    isPremium: false,
    claimed: false,
    rating: 4.8,
    reviewsCount: 42
  },
  {
    id: 'e8',
    name: 'Casa Barro Sol - Ateliê Olinda',
    category: 'Ateliê',
    specialties: ['Modelagem Manual', 'Azulejaria', 'Baixa Temperatura', 'Cerâmica Contemporânea'],
    services: ['Oficinas Criativas', 'Queima de Baixo Custo'],
    privacy: 'full',
    address: 'Rua do Amparo, 230',
    neighborhood: 'Amparo',
    city: 'Olinda',
    state: 'PE',
    coordinates: [-8.0125, -34.8482],
    description: 'Casarão histórico em Olinda unindo a tradição dos azulejos pernambucanos pintados à mão e modelagens poéticas de figuras do imaginário nordestino.',
    instagram: '@barrosol_olinda',
    whatsapp: '81995551212',
    photo: 'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?auto=format&fit=crop&w=800&q=80',
    isPremium: true,
    claimed: true,
    ownerId: 'ownerOlinda',
    rating: 4.7,
    reviewsCount: 19,
    hours: 'Quarta a Domingo: 13:00 às 19:00',
    viewsCount: 167,
    clicksWhatsApp: 38,
    clicksRoute: 19,
    events: [
      {
        id: 'ev4',
        title: 'Oficina de Azulejaria Tradicional',
        type: 'workshop',
        date: '2026-07-25',
        time: '14:00 - 18:00',
        price: 'R$ 180',
        instructor: 'Mestre Gilberto',
        description: 'Aprenda as técnicas de decalque e pintura sob esmalte aplicados em azulejos coloniais, com queima inclusa.',
        location: 'Pátio interno da Casa Barro Sol',
        establishmentId: 'e8'
      }
    ]
  },
  {
    id: 'e9',
    name: 'Assistência Técnica Shima Fornos',
    category: 'Assistência Técnica',
    specialties: ['Queima Elétrica', 'Queima a Gás'],
    services: ['Conserto de Fornos', 'Instalação Elétrica de Carga', 'Troca de Resistências', 'Calibração de Controladores'],
    privacy: 'full',
    address: 'Rua do Gasômetro, 345',
    neighborhood: 'Brás',
    city: 'São Paulo',
    state: 'SP',
    coordinates: [-23.5422, -46.6185],
    description: 'Especialista em manutenção preventiva e corretiva de fornos cerâmicos de todas as marcas. Venda de fios de resistência e refratários.',
    instagram: '@shima_fornos',
    whatsapp: '11966663333',
    photo: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    isPremium: false,
    claimed: true,
    ownerId: 'ownerShima',
    rating: 4.9,
    reviewsCount: 31
  },
  {
    id: 'e10',
    name: 'Ateliê Brasília Queima Escultural',
    category: 'Ateliê',
    specialties: ['Alta Temperatura', 'Modelagem Manual', 'Porcelana'],
    services: ['Cursos Regulares', 'Queima Compartilhada'],
    privacy: 'full',
    address: 'CLN 115 Bloco C',
    neighborhood: 'Asa Norte',
    city: 'Brasília',
    state: 'Distrito Federal',
    coordinates: [-15.7538, -47.8827],
    description: 'Espaço contemporâneo dedicado ao ensino da modelagem figurativa e abstrata no coração do Plano Piloto de Brasília.',
    instagram: '@bsb_queima_escultural',
    whatsapp: '61999998888',
    photo: 'https://images.unsplash.com/photo-1565192647048-f997ded879f9?auto=format&fit=crop&w=800&q=80',
    isPremium: true,
    claimed: true,
    ownerId: 'ownerBsbEscultural',
    rating: 4.9,
    reviewsCount: 14,
    hours: 'Segunda a Sexta: 14:00 às 21:00\nSábado: 09:00 às 13:00'
  },
  {
    id: 'e11',
    name: 'Cerâmica da Terra - Plano Piloto',
    category: 'Ateliê Escola',
    specialties: ['Torno', 'Modelagem Manual', 'Alta Temperatura'],
    services: ['Aulas Regulares', 'Workshops', 'Venda de Argila'],
    privacy: 'neighborhood',
    address: 'CLS 312 Bloco B',
    neighborhood: 'Asa Sul',
    city: 'Brasília',
    state: 'DF',
    coordinates: [-15.8085, -47.8992],
    description: 'Ateliê escola focado no desenvolvimento artístico de ceramistas iniciantes e avançados com tornos de alta performance.',
    instagram: '@ceramicadaterra_df',
    whatsapp: '61988881111',
    photo: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=800&q=80',
    isPremium: false,
    claimed: false,
    rating: 4.7,
    reviewsCount: 8
  },
  {
    id: 'e12',
    name: 'Mestre do Barro Taguatinga',
    category: 'Ceramista',
    specialties: ['Cerâmica Popular', 'Modelagem Manual', 'Escultura'],
    services: ['Visita Agendada', 'Encomendas Personalizadas'],
    privacy: 'full',
    address: 'QND 25 Casa 4',
    neighborhood: 'Taguatinga Norte',
    city: 'Brasília',
    state: 'Distrito Fed.',
    coordinates: [0, 0],
    description: 'Ateliê de modelagem manual preservando a tradição da modelagem de utilitários de barro cru e cerâmica terracota regional.',
    instagram: '@mestre_barro_taguatinga',
    whatsapp: '61977772222',
    photo: 'https://images.unsplash.com/photo-1590736969955-71cb94801750?auto=format&fit=crop&w=800&q=80',
    isPremium: false,
    claimed: false,
    rating: 4.6,
    reviewsCount: 3
  }
];

export const MOCK_SHEETS_DATA: SyncRow[] = [
  {
    id: 's_row_1',
    timestamp: '2026-06-29 10:14:22',
    name: 'Ateliê Lua Cheia Cerâmica',
    category: 'Ateliê',
    state: 'RJ',
    city: 'Paraty',
    address: 'Rua do Fogo, 12',
    neighborhood: 'Centro Histórico',
    contact: '@luacheiaceramica',
    specialties: 'Modelagem Manual, Torno, Baixa Temperatura, Alta Temperatura',
    status: 'pending'
  },
  {
    id: 's_row_2',
    timestamp: '2026-06-29 11:25:05',
    name: 'Pascoal Argilas (Filial)',
    category: 'Fornecedor',
    state: 'SP',
    city: 'São Paulo',
    address: 'Av. Ricardo Jafet, 1850', // Duplicado de e3!
    neighborhood: 'Ipiranga',
    contact: '11977771111',
    specialties: 'Alta Temperatura, Baixa Temperatura',
    status: 'duplicate'
  },
  {
    id: 's_row_3',
    timestamp: '2026-06-29 13:42:19',
    name: 'Mesa de Barro - Regina G.',
    category: 'Ceramista',
    state: 'MG',
    city: 'Tiradentes',
    address: 'Rua Direita, 25',
    neighborhood: 'Centro',
    contact: '@mesadebarro',
    specialties: 'Modelagem Manual, Queima a Lenha, Cerâmica Popular',
    status: 'pending'
  },
  {
    id: 's_row_4',
    timestamp: '2026-06-29 14:05:00',
    name: 'Ateliê soteropolitano',
    category: 'Ateliê',
    state: 'BA',
    city: 'Salvador',
    address: 'Rua Carmo, 102',
    neighborhood: 'Santo Antônio Além do Carmo',
    contact: '71988112233',
    specialties: 'Raku, Torno, Cerâmica Contemporânea',
    status: 'pending'
  }
];

export const INITIAL_SYNC_LOGS: SyncLog[] = [
  {
    id: 'log1',
    timestamp: '2026-06-15 09:00:00',
    action: 'Importação Inicial de Planilha de Lançamento',
    recordsSynced: 120,
    recordsIgnored: 5,
    operator: 'Admin Sistema'
  },
  {
    id: 'log2',
    timestamp: '2026-06-22 18:30:12',
    action: 'Sincronização agendada automática - Planilha Geral de Colaboradores',
    recordsSynced: 14,
    recordsIgnored: 2,
    operator: 'Sistema Cron'
  }
];

export const DEFAULT_PLANS: PlanConfig[] = [
  {
    id: 'gratuito',
    name: 'Perfil Oficial Gratuito',
    price: 0,
    period: 'Sempre',
    features: [
      'Presença básica no mapa nacional',
      'Informações de contato (WhatsApp/Instagram)',
      '1 foto ilustrativa',
      'Descrição resumida',
      'Participação nas buscas básicas',
      'Selos de perfil verificado e oficial'
    ],
    maxPhotos: 1,
    maxVideos: 0,
    hasSearchProminence: false,
    hasMapHighlight: false,
    hasHomeHighlight: false
  },
  {
    id: 'atelie',
    name: 'Plano Ateliê',
    price: 39,
    period: 'Mês',
    features: [
      'Todos os recursos do perfil gratuito',
      'Galeria com até 4 fotos ilustrativas',
      'Logo do espaço',
      'História completa do ateliê (texto longo)',
      'Listagem de serviços prestados',
      'Listagem de cursos regulares',
      'Horários de atendimento',
      'Website e links adicionais',
      'Destaque médio nas pesquisas'
    ],
    maxPhotos: 4,
    maxVideos: 0,
    hasSearchProminence: true,
    hasMapHighlight: false,
    hasHomeHighlight: false
  },
  {
    id: 'estudio',
    name: 'Plano Estúdio',
    price: 79,
    period: 'Mês',
    features: [
      'Todos os recursos do Plano Ateliê',
      'Galeria ampliada (até 10 fotos)',
      'Banner/Capa customizável',
      'Agenda integrada de cursos e workshops',
      'Agenda de eventos e exposições',
      'Vídeo de apresentação incorporado',
      'Catálogo/Vitrine de produtos e peças',
      'Painel estatístico com contagem de cliques',
      'Botões personalizados na ficha',
      'Destaque no mapa nacional e página inicial'
    ],
    maxPhotos: 10,
    maxVideos: 1,
    hasSearchProminence: true,
    hasMapHighlight: true,
    hasHomeHighlight: true
  },
  {
    id: 'institucional',
    name: 'Plano Institucional',
    price: 199,
    period: 'Mês',
    features: [
      'Destinado a Fornecedores, Associações, Museus e Escolas',
      'Múltiplas unidades ou filiais no mapa',
      'Catálogo completo de materiais e equipamentos',
      'Banners promocionais rotativos',
      'Página institucional customizada ampliada',
      'Campanhas e anúncios com link externo',
      'Área de download de catálogos e documentos',
      'Prioridade máxima em buscas e recomendações',
      'Integração prioritária com futuro marketplace'
    ],
    maxPhotos: 20,
    maxVideos: 3,
    hasSearchProminence: true,
    hasMapHighlight: true,
    hasHomeHighlight: true
  }
];

export const INITIAL_SUGGESTED_SPACES: SuggestedSpace[] = [
  {
    id: 'sug_1',
    name: 'Cerâmica de Cunha Noborigama',
    category: 'Ateliê',
    city: 'Cunha',
    state: 'SP',
    neighborhood: 'Vila Rica',
    contact: '@ceramica_art_cunha',
    specialties: 'Noborigama, Queima a Lenha',
    suggestedBy: 'Amanda Ferreira',
    date: '2026-06-28 10:20',
    invitedStatus: 'pending'
  },
  {
    id: 'sug_2',
    name: 'Suprimentos Cerâmicos do Sul',
    category: 'Fornecedor',
    city: 'Porto Alegre',
    state: 'RS',
    neighborhood: 'Passo d\'Areia',
    contact: '51988776655',
    specialties: 'Alta Temperatura, Argila',
    suggestedBy: 'Rodrigo Lima',
    date: '2026-06-29 11:15',
    invitedStatus: 'invited'
  }
];

export const DEFAULT_INTEGRATION_CONFIG: IntegrationConfig = {
  url: 'https://docs.google.com/spreadsheets/d/1mUr3cwLDMe5DIufp2n5zH8S3955Z58A6lJqq1o0ULYs/edit?usp=sharing',
  spreadsheetId: '1mUr3cwLDMe5DIufp2n5zH8S3955Z58A6lJqq1o0ULYs',
  sheetName: 'Respostas do formulário 1',
  syncInterval: 30, // 30 seconds default
  syncMethod: 'automatic',
  status: 'active'
};

